# pnpm workspace configuration
# https://pnpm.io/workspaces

packages:
  # Core framework packages
  - 'packages/*'
  
  # Production applications built with Gati
  - 'apps/*'
  
  # Example applications
  - 'examples/*'
  
  # Main source (if published as @gati-framework/core)
  - 'src'
