{{- if and .Values.ingress.enabled .Values.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: gati-ingress
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: gati-ingress
    app.kubernetes.io/component: ingress
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  minAvailable: {{ .Values.pdb.minAvailable }}
  selector:
    matchLabels:
      app.kubernetes.io/name: gati-ingress
      app.kubernetes.io/component: ingress
{{- end }}
