{{- if and .Values.ingress.enabled .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gati-ingress
  namespace: {{ .Values.serviceMonitor.namespace }}
  labels:
    app.kubernetes.io/name: gati-ingress
    app.kubernetes.io/component: ingress
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    {{- with .Values.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: gati-ingress
      app.kubernetes.io/component: ingress
  namespaceSelector:
    matchNames:
    - {{ .Values.global.namespace }}
  endpoints:
  - port: http
    path: {{ .Values.serviceMonitor.path }}
    interval: {{ .Values.serviceMonitor.interval }}
    honorLabels: true
{{- end }}
